### ISSUE TITLE
Split zim not recognized by kiwix android app

### ISSUE THREAD

**Issue by rodrigoSantamaria** [kiwix/overview#37]
Hi there,
I downloaded wikipedia_en_all_nopic_2020_04.zim (39.3G) and tried to put it into a SD card which does not hold files larger than 4G. So, according to my kiwix app help I splitted it with split --bytes and got the files .zimaa to .zimaj and copied them succesfully to the SD card (same folder as other zims)
But when I go to my kiwix app and update local zims on 'get content', I cannot see the new wiki. Mi app is running in Android (version 2.1 build 45)
I can format the SD card for a format that accepts >4G files, but I'd prefer not to.

Thanks a lot, great app!

**Comment by kelson42** [comment]
Hi @rodrigoSantamaria 

This is not supported anymore and not part of the help of recent versions.

I recomment to use latest version of Kiwix for Android.

That said, that does not solve your problem. I recommend to use a SD card formated with exFAT which can deal with bigger files (but I know that not all Android devices can deal with them).

Unfortunately this is the best we can say for now. We have removed (for now) the support of splitted ZIM files because this was too cumbersome to maintain.

Kind regards
Emmanuel

**Comment by rodrigoSantamaria** [comment]
Hi Emmanuel, 
Just wanted to let you know that, after updating to version 3.1.3 Build:230103 in Android, it get's perfectly the content of the _splitted_ wikipedia_en_all_nopic_2020_04.zim (39.3G)!

Cheers,
Rodrigo

**Comment by kelson42** [comment]
@rodrigoSantamaria Trust me it does not work perfectly! But happy you are a satisfied user :)

**Comment by rodrigoSantamaria** [comment]
Good enough so far :)
Always satisfied about an interesting free source project and grateful to the people behind!

**Comment by kelson42** [comment]
@rodrigoSantamaria Thank you. Much appreciated. Not obvious for a lot of people unfortunately!
