### ISSUE TITLE
kiwix for amazon kindle [Oasis and paperwhite]

### ISSUE THREAD

**Issue by zevisvei** [kiwix/overview#76]
I don't think it's Android-based, but I saw that there was an option to install games and applications [[see here](https://www.amazon.com/s?k=active+content+kindle+paperwhite&crid=LK1YYPV6ZHBT&sprefix=active+content%2Caps%2C207&ref=nb_sb_ss_ts-doa-p_1_14)], so I thought maybe it would be possible to develop Kiwix for the Kindle as well.
Or maybe As a browser extension for the built-in browser

**Comment by kelson42** [comment]
I think this tickey is a duplicate of https://github.com/kiwix/kiwix-android/issues/132

**Comment by zevisvei** [comment]
Not accurate, the Kindle Oasis and paperwhite doesn't even have an Amazon app store, so I suggested that it be a browser add-on or a Kindle application

**Comment by kelson42** [comment]
Honestly I don't think we will go for that in a near future because:
* We are really supportive and interested to find tablets running Kiwix, but considering how closed is Kindle, this is probably one of the last one we would go for.
* We don't really have the resources and it does not belong to the priorities

**Comment by leahanderson1** [comment]
> Not accurate, the Kindle Oasis and paperwhite doesn't even have an Amazon app store, so I suggested that it be a browser add-on or a Kindle application

how about homebrew?
AFAIK the kindle eink OS is just an embedded linux system running a java UI
there are countless exploits to run your own code on it
if you need an example of an implementation of a kindle homebrew reader, check out KOReader

**Comment by kelson42** [comment]
@leahanderson1 We can not build something specific for one model of reader because of lack of resources. We won't rely on a hack to build something official. The way to go is Android for the moment, and the support of e-ink devices will be included in next major release of Kiwix for Android: 4.0.0. Closing as there is nothing more we can do here. See https://github.com/kiwix/kiwix-android/issues/3521
