### ISSUE TITLE
Torrent served only as webseed

### ISSUE THREAD

**Issue by JensKorte** [kiwix/overview#94]
The client is transmission-gtk. The file gets downloaded from the web seed.

![kiwix](https://github.com/kiwix/overview/assets/2682123/e08e6c6b-4fd7-4ac2-9a87-91f459fcbc23)

**Comment by rgaudin** [comment]
Will look it up

**Comment by kelson42** [comment]
@JensKorte Thank you for reporting, is worrying indeed.

**Comment by rgaudin** [comment]
@JensKorte that's a good catch because, first the download still works (using the webseed) so it has to be seen and also because it only affects a handful of ZIM files:

* https://download.kiwix.org/zim/wikiversity/wikiversity_it_all_maxi_2023-06.zim.meta4
* https://download.kiwix.org/zim/wikipedia/wikipedia_fr_all_maxi_2023-06.zim.meta4
* https://download.kiwix.org/zim/ted/teded_en_all_2023-07.zim.meta4
* https://download.kiwix.org/zim/wikipedia/wikipedia_nl_all_maxi_2023-07.zim.meta4
* https://download.kiwix.org/zim/ted/ted_en_business_2023-07.zim.meta4
* https://download.kiwix.org/zim/vikidia/vikidia_it_all_maxi_2023-07.zim.meta4
* https://download.kiwix.org/zim/wikipedia/wikipedia_ro_all_nopic_2023-07.zim.meta4
* https://download.kiwix.org/zim/wikipedia/wikipedia_de_all_maxi_2023-08.zim.meta4

As you can see, it's exclusively large ZIMs. What happens is that out tracker syncs every hour to find out about new ZIMs by querying the OPDS catalog.
With large ZIMs, it is possible the ZIMs is on the master mirror, where the library is built and thus exposed via OPDS but not yet processed by mirrorbrain… so the `.btih` link is not ready and returns a 404.
The script was not accounting for this and would thus add an entry for the failed ZIM (with garbage content)

Fixed in https://github.com/kiwix/container-images/commit/4925a33286f710ed8c178e12a0fae8594345e0a8

<img width="1008" alt="Screenshot 2023-08-21 at 11 13 28" src="https://github.com/kiwix/overview/assets/57929/adbb630b-61d7-47d0-b043-2cdda4c5ab62">

**Comment by JensKorte** [comment]
Thank you for the explanation!

**Comment by JensKorte** [comment]
I got the same error for the english wp.

![kiwix](https://github.com/kiwix/overview/assets/2682123/3738946d-02dd-409f-9b04-478a5481fd30)

**Comment by rgaudin** [comment]
Thanks again! There was indeed another bug preventing opentracker from reloading.
Fixed in https://github.com/kiwix/container-images/commit/249f2ecfb77994342079289d1db47da28b53b58b
